{
 "title": "Node",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node_load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"node\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_load5{job=\"node\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_load15{job=\"node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MemFree (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FS available (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}